apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: website-resume
  newName: rafaelcecchin/website-resume
  newTag: 91c7dc2cb10c0da24d78edc590c107aa7e152685
