apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: website-resume
  newName: rafaelcecchin/website-resume
  newTag: 1ec8e0a7839a8902aea9188296bf2daa44237fa7
